/*     */ package br.com.deckbuilder.view;
/*     */ 
import br.com.deckbuilder.controller.DAOCard;
import br.com.deckbuilder.controller.UtilsCarta;
import br.com.deckbuilder.model.Card;
import java.awt.Color;
/*     */ import java.awt.EventQueue;
/*     */ import java.awt.event.ActionEvent;
/*     */ import java.awt.event.FocusEvent;
/*     */ import java.awt.event.ItemEvent;
/*     */ import java.awt.event.MouseEvent;
import javax.swing.JButton;
/*     */ import javax.swing.JFrame;
/*     */ import javax.swing.JOptionPane;


/*     */ 
/*     */ public class CriaCarta extends JFrame
/*     */ {
/*  16 */   //String nome = "";
/*     */   public Object tipoCarta;
/*     */   public String tipoCartaS;
/*     */   public String custoS;
/*     */   public Object tipoCusto;
/*     */   public int i;
/*     */   public int qtdCartas;

 public JButton[] listaStr = new JButton[18];

public void criaVetor() {
        listaStr[0] = btnCard1;
        listaStr[1] = btnCard2;
        listaStr[2] = btnCard3;
        listaStr[3] = btnCard4;
        listaStr[4] = btnCard5;
        listaStr[5] = btnCard6;
        listaStr[6] = btnCard7;
        listaStr[7] = btnCard8;
        listaStr[8] = btnCard9;
        listaStr[9] = btnCard10;
        listaStr[10] = btnCard11;
        listaStr[11] = btnCard12;
        listaStr[12] = btnCard13;
        listaStr[13] = btnCard14;
        listaStr[14] = btnCard15;
        listaStr[15] = btnCard16;
        listaStr[16] = btnCard17;
        listaStr[17] = btnCard18;
        
        
    }
private static CriaCarta singleton;


public static CriaCarta getInstance(){
            if(CriaCarta.singleton == null){
            CriaCarta.singleton = new CriaCarta ();
        }
        return CriaCarta.singleton;
    }

    public void escolheCarta(String panelId) {
        int flagCardSelected = 0;
       
        
     if(flagCardSelected == 0){
       for (int iCard=0; iCard < listaStr.length; iCard++)
        {
            if (panelId.equals(listaStr[iCard].getName()))
            {
                listaStr[iCard].setBackground(Color.yellow);
                Card card = Card.getInstance();
                card.setImage(panelId);
                System.out.println(card.getImage());
                //flagCardSelected = 1;
            }
        }
     }
     else {
JOptionPane.showMessageDialog(null, "Você só pode escolher uma imagem por carta!");
     }
    }
       
/*     */   public CriaCarta()
/*     */   {
/*  36 */     initComponents();

this.setExtendedState(MAXIMIZED_BOTH); 
/*     */ 
/*  38 */     this.jLabel14.setVisible(false);
/*  39 */     this.jLabel15.setVisible(false);
/*  40 */     this.txtAtaque.setVisible(false);
/*  41 */     this.txtDefesa.setVisible(false);
/*     */ 
/*  43 */     this.jLabel9.setVisible(false);
/*  44 */     this.jLabel10.setVisible(false);
/*  45 */     this.jLabel11.setVisible(false);
/*  46 */     this.jLabel13.setVisible(false);
/*  47 */     this.cboCusto.setVisible(false);
/*  48 */     this.txtTipoCusto.setVisible(false);
/*  49 */     this.txtQtdCusto.setVisible(false);



/*     */   }
/*     */
        //Construtor para edição da carta
        public CriaCarta(Card card)
/*     */   {
/*  36 */     initComponents();
              this.setCardData(card);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deckName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mskQtdCarta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboTipoCarta = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        PanImagem = new javax.swing.JPanel();
        btnCard1 = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard4 = new javax.swing.JButton();
        btnCard5 = new javax.swing.JButton();
        btnCard6 = new javax.swing.JButton();
        btnCard7 = new javax.swing.JButton();
        btnCard8 = new javax.swing.JButton();
        btnCard9 = new javax.swing.JButton();
        btnCard10 = new javax.swing.JButton();
        btnCard11 = new javax.swing.JButton();
        btnCard12 = new javax.swing.JButton();
        btnCard13 = new javax.swing.JButton();
        btnCard14 = new javax.swing.JButton();
        btnCard15 = new javax.swing.JButton();
        btnCard16 = new javax.swing.JButton();
        btnCard17 = new javax.swing.JButton();
        btnCard18 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNomeCarta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboCusto = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtQtdCusto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTipoCusto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacoes = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JFormattedTextField();
        txtDefesa = new javax.swing.JFormattedTextField();
        btnFinalizarDeck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("CreateDeckForm"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Criando o Deck");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        deckName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deckName.setText("deck");
        getContentPane().add(deckName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Características Gerais de nova carta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        getContentPane().add(mskQtdCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 40, -1));

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cboTipoCarta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo", "Criatura", "Mágica", "Recurso" }));
        cboTipoCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboTipoCartaMouseEntered(evt);
            }
        });
        cboTipoCarta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoCartaItemStateChanged(evt);
            }
        });
        cboTipoCarta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboTipoCartaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboTipoCartaFocusLost(evt);
            }
        });
        getContentPane().add(cboTipoCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setText("Imagem:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        PanImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanImagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/gigante_de_pedra.jpg"))); // NOI18N
        btnCard1.setName("btnCard1"); // NOI18N
        btnCard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 110));

        btnCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/bola_de_fogo.jpg"))); // NOI18N
        btnCard2.setName("btnCard2"); // NOI18N
        btnCard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 110));

        btnCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/gilfor.jpg"))); // NOI18N
        btnCard3.setName("btnCard3"); // NOI18N
        btnCard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });
        PanImagem.add(btnCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 110));

        btnCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/bomba_atomica.jpg"))); // NOI18N
        btnCard4.setName("btnCard4"); // NOI18N
        btnCard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 110));

        btnCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/maldicao.jpg"))); // NOI18N
        btnCard5.setName("btnCard5"); // NOI18N
        btnCard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 80, 110));

        btnCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/buraco.jpg"))); // NOI18N
        btnCard6.setName("btnCard6"); // NOI18N
        btnCard6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 110));

        btnCard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/homem_aguia.jpg"))); // NOI18N
        btnCard7.setName("btnCard7"); // NOI18N
        btnCard7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 110));

        btnCard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/cyborg_assassino.jpg"))); // NOI18N
        btnCard8.setName("btnCard8"); // NOI18N
        btnCard8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 110));

        btnCard9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/planta_lunatica.jpg"))); // NOI18N
        btnCard9.setName("btnCard9"); // NOI18N
        btnCard9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, 110));

        btnCard10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/fantasma.jpg"))); // NOI18N
        btnCard10.setName("btnCard10"); // NOI18N
        btnCard10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 80, 110));

        btnCard11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/sapo_macabro.jpg"))); // NOI18N
        btnCard11.setName("btnCard11"); // NOI18N
        btnCard11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, 110));

        btnCard12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/flighter.jpg"))); // NOI18N
        btnCard12.setName("btnCard12"); // NOI18N
        btnCard12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 80, 110));

        btnCard13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/veneno.jpg"))); // NOI18N
        btnCard13.setName("btnCard13"); // NOI18N
        btnCard13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 110));

        btnCard14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/titan.jpg"))); // NOI18N
        btnCard14.setName("btnCard14"); // NOI18N
        btnCard14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 110));

        btnCard15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/radiacao.jpg"))); // NOI18N
        btnCard15.setName("btnCard15"); // NOI18N
        btnCard15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 110));

        btnCard16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/explosivo 1.jpg"))); // NOI18N
        btnCard16.setName("btnCard16"); // NOI18N
        btnCard16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, 110));

        btnCard17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/el_tigre.jpg"))); // NOI18N
        btnCard17.setName("btnCard17"); // NOI18N
        btnCard17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 80, 110));

        btnCard18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/anula_magia.jpg"))); // NOI18N
        btnCard18.setName("btnCard18"); // NOI18N
        btnCard18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBorder(evt);
            }
        });
        PanImagem.add(btnCard18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, 110));

        getContentPane().add(PanImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 500, 350));

        jLabel8.setText("Nome:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(txtNomeCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        jLabel9.setText("Custo para ser usada:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        cboCusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum", "Outro" }));
        cboCusto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCustoItemStateChanged(evt);
            }
        });
        cboCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCustoActionPerformed(evt);
            }
        });
        getContentPane().add(cboCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel10.setText("Quantidade");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));
        getContentPane().add(txtQtdCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 40, -1));

        jLabel11.setText("Tipo do Custo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));
        getContentPane().add(txtTipoCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 130, -1));

        jLabel12.setText("Texto Descritivo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtInformacoes.setColumns(20);
        txtInformacoes.setRows(5);
        jScrollPane1.setViewportView(txtInformacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 60));

        jLabel13.setText("de Custo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel14.setText("Ataque:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel15.setText("Defesa:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        txtAtaque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtAtaque.setToolTipText("");
        getContentPane().add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 40, -1));

        txtDefesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(txtDefesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 40, -1));

        btnFinalizarDeck.setText("Finalizar Deck");
        btnFinalizarDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarDeckMouseClicked(evt);
            }
        });
        getContentPane().add(btnFinalizarDeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 630, -1, -1));

        jButton2.setText("Habilidades");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*     */ 
/*     */   private void cboTipoCartaFocusGained(FocusEvent evt){//GEN-FIRST:event_cboTipoCartaFocusGained

/*     */   }//GEN-LAST:event_cboTipoCartaFocusGained
/*     */ 
/*     */   private void cboTipoCartaFocusLost(FocusEvent evt) {//GEN-FIRST:event_cboTipoCartaFocusLost
/*     */   }//GEN-LAST:event_cboTipoCartaFocusLost
/*     */ 
/*     */   private void cboTipoCartaMouseEntered(MouseEvent evt) {//GEN-FIRST:event_cboTipoCartaMouseEntered

/*     */   }//GEN-LAST:event_cboTipoCartaMouseEntered
/*     */ 
/*     */   private void cboTipoCartaItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_cboTipoCartaItemStateChanged
/* 257 */     this.tipoCarta = this.cboTipoCarta.getSelectedItem();
/* 258 */     this.tipoCartaS = this.tipoCarta.toString();
/*     */ 
/* 260 */     if ((this.tipoCarta == "Mágica") || (this.tipoCarta == "Recurso")) {
/* 261 */       this.jLabel14.setVisible(false);
/* 262 */       this.jLabel15.setVisible(false);
/* 263 */       this.txtAtaque.setVisible(false);
/* 264 */       this.txtDefesa.setVisible(false);
/* 265 */       this.jLabel9.setVisible(true);
/* 266 */       this.cboCusto.setVisible(true);
/*     */     }
/*     */ 
/* 269 */     if (this.tipoCarta == "Criatura") {
/* 270 */       this.jLabel14.setVisible(true);
/* 271 */       this.jLabel15.setVisible(true);
/* 272 */       this.txtAtaque.setVisible(true);
/* 273 */       this.txtDefesa.setVisible(true);
/* 274 */       this.jLabel9.setVisible(true);
/* 275 */       this.cboCusto.setVisible(true);
/*     */     }
/*     */ 
/* 278 */    tipoCartaS = UtilsCarta.converteCarta(tipoCarta.toString());
/*     */   }//GEN-LAST:event_cboTipoCartaItemStateChanged
/*     */ 
/*     */   private void cboCustoItemStateChanged(ItemEvent evt){//GEN-FIRST:event_cboCustoItemStateChanged
/* 292 */     this.tipoCusto = this.cboCusto.getSelectedItem();
/*     */ 
/* 294 */     if (this.tipoCusto == "Outro") {
/* 295 */       this.jLabel10.setVisible(true);
/* 296 */       this.jLabel11.setVisible(true);
/* 297 */       this.jLabel13.setVisible(true);
/* 298 */       this.txtTipoCusto.setVisible(true);
/* 299 */       this.txtQtdCusto.setVisible(true);
/*     */     }
/*     */     else {
/* 302 */       this.jLabel10.setVisible(false);
/* 303 */       this.jLabel11.setVisible(false);
/* 304 */       this.jLabel13.setVisible(false);
/* 305 */       this.txtTipoCusto.setVisible(false);
/* 306 */       this.txtQtdCusto.setVisible(false);
/*     */     }

/*     */   }//GEN-LAST:event_cboCustoItemStateChanged
/*     */ 
/*     */   private void cboCustoActionPerformed(ActionEvent evt){//GEN-FIRST:event_cboCustoActionPerformed

/*     */   }//GEN-LAST:event_cboCustoActionPerformed


    private void btnFinalizarDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarDeckMouseClicked
                  DAOCard daoCard =  DAOCard.getInstance();
                  
                 
                  daoCard.commitCards();
                   JOptionPane.showMessageDialog(null, "Deck SALVO!");
    }//GEN-LAST:event_btnFinalizarDeckMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        Card card =  Card.getInstance();
            this.tipoCusto = this.cboCusto.getSelectedItem();
            String ataque = null;
            String defesa = null;

/* 318 */     if (this.tipoCusto == "Nenhum") {
/* 319 */       this.custoS = "none";
                card.setCusto(custoS);
/*     */     }
/*     */     else {
/* 322 */       this.custoS = this.txtTipoCusto.getText();
card.setCusto(custoS);
/*     */     }
    this.qtdCartas = Integer.parseInt(this.mskQtdCarta.getText());              
/*  66 */     card.setType(this.tipoCartaS);
/*  67 */     card.setNome(this.txtNomeCarta.getText());
/*  68 */     card.setInformacoes(this.txtInformacoes.getText());
/*  69 */     card.setCusto(this.custoS);

if(ataque == null){
card.setForca("none");
}
/*  70 */     card.setForca(this.txtAtaque.getText());
if(defesa == null){
card.setDefesa("none");
}
/*  71 */     card.setDefesa(this.txtDefesa.getText());
              card.setQtd(qtdCartas);
              
               CriaHabilidade criaHabilidade = new CriaHabilidade();
/* 340 */       criaHabilidade.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void changeBorder(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBorder
       // System.out.println(evt.getComponent().getName());
        this.escolheCarta(evt.getComponent().getName());
    }//GEN-LAST:event_changeBorder

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     criaVetor();
         TelaInicial telaInicial = TelaInicial.getInstance();
    deckName.setText(telaInicial.deckName);
    }//GEN-LAST:event_formWindowActivated

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard3ActionPerformed

    /**
     * @param args the command line arguments
     */
/*     */   public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/* 389 */     EventQueue.invokeLater(new Runnable() {
/*     */       public void run() {
/* 391 */           // new teste().setVisible(true);
/* 392 */         CriaCarta criaCarta = new CriaCarta();
 criaCarta.setVisible(true);
/*     */       }
/*     */     });
/*     */   }

 private void setCardData(Card card){
        //this.cboTipoCarta.setSelectedItem(UtilsCarta.converteCarta(card.getType()));
        this.txtNomeCarta.setText(card.getNome());
        this.txtAtaque.setText(card.getForca());
        this.txtDefesa.setText(card.getDefesa());
        this.txtInformacoes.setText(card.getInformacoes());
        this.txtTipoCusto.setText(card.getCusto());
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanImagem;
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard10;
    private javax.swing.JButton btnCard11;
    private javax.swing.JButton btnCard12;
    private javax.swing.JButton btnCard13;
    private javax.swing.JButton btnCard14;
    private javax.swing.JButton btnCard15;
    private javax.swing.JButton btnCard16;
    private javax.swing.JButton btnCard17;
    private javax.swing.JButton btnCard18;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnCard4;
    private javax.swing.JButton btnCard5;
    private javax.swing.JButton btnCard6;
    private javax.swing.JButton btnCard7;
    private javax.swing.JButton btnCard8;
    private javax.swing.JButton btnCard9;
    private javax.swing.JButton btnFinalizarDeck;
    private javax.swing.JComboBox cboCusto;
    private javax.swing.JComboBox cboTipoCarta;
    private javax.swing.JLabel deckName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField mskQtdCarta;
    public javax.swing.JFormattedTextField txtAtaque;
    public javax.swing.JFormattedTextField txtDefesa;
    public javax.swing.JTextArea txtInformacoes;
    public javax.swing.JTextField txtNomeCarta;
    private javax.swing.JTextField txtQtdCusto;
    private javax.swing.JTextField txtTipoCusto;
    // End of variables declaration//GEN-END:variables
}

