/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.deckbuilder.view;

import br.com.deckbuilder.controller.DAOCard;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Yasmin
 */



public class TelaInicial extends javax.swing.JFrame {

    public String deckName;
    public int flagCaminho = 0;

    private static TelaInicial singleton;



public static TelaInicial getInstance(){
            if(TelaInicial.singleton == null){
            TelaInicial.singleton = new TelaInicial ();
        }
        return TelaInicial.singleton;
    }

    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCaminhoModificar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeDeck = new javax.swing.JTextField();
        botCriarDeck = new javax.swing.JButton();
        botAlterarDeck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setForeground(new java.awt.Color(255, 0, 255));
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bem vindo ao Deck Builder Mnemosyne");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mnemosyne/resources/images/search.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 111, 50, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("É muito fácil começar!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 61, -1, -1));

        jLabel3.setText("Se você quer modificar seu Deck encontre-o aqui:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 101, -1, -1));

        txtCaminhoModificar.setEditable(false);
        txtCaminhoModificar.setText("\n");
        txtCaminhoModificar.setEnabled(false);
        txtCaminhoModificar.setName("teste"); // NOI18N
        txtCaminhoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaminhoModificarActionPerformed(evt);
            }
        });
        txtCaminhoModificar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCaminhoModificarPropertyChange(evt);
            }
        });
        getContentPane().add(txtCaminhoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, 460, -1));

        jLabel4.setText("Ou crie um novo Deck aqui:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, -1));

        jLabel5.setText("Título do Deck:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 231, -1, -1));
        getContentPane().add(txtNomeDeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 251, 268, -1));

        botCriarDeck.setText("Criar!");
        botCriarDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botCriarDeckMouseClicked(evt);
            }
        });
        botCriarDeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCriarDeckActionPerformed(evt);
            }
        });
        getContentPane().add(botCriarDeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 251, -1, 20));

        botAlterarDeck.setText("Alterar");
        botAlterarDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botAlterarDeckMouseClicked(evt);
            }
        });
        getContentPane().add(botAlterarDeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 161, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
String caminhoArquivo = "";
/*     */ 
/* 132 */     JFileChooser arquivo = new JFileChooser();
/* 133 */     arquivo.setDialogTitle("Selecione seu Deck");
/*     */ 
/* 135 */     arquivo.setFileFilter(new FileFilter()
/*     */     {
/*     */       public boolean accept(File f) {
/* 138 */         return (f.getName().toLowerCase().endsWith(".xml")) || (f.isDirectory());
/*     */       }
/*     */ 
/*     */       public String getDescription() {
/* 142 */         return "Arquivos de deck (.xml)";
/*     */       }
/*     */     });
/* 147 */     int retorno = arquivo.showOpenDialog(null);
/* 148 */     if (retorno == 0) {
/* 149 */       caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
/*     */     }
/*     */ 
/* 155 */     this.txtCaminhoModificar.setText(caminhoArquivo);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botCriarDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCriarDeckMouseClicked
deckName = txtNomeDeck.getText();
/*     */ 
/* 177 */     CriaDeck criaDeck = new CriaDeck();
/* 178 */     criaDeck.setVisible(true);
/* 179 */   this.setVisible(false);
    }//GEN-LAST:event_botCriarDeckMouseClicked

    private void botCriarDeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCriarDeckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botCriarDeckActionPerformed

    private void botAlterarDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botAlterarDeckMouseClicked
if(txtCaminhoModificar.getText() != null){
        DAOCard daoCard = new DAOCard();
        try {
            daoCard.loadCard(txtCaminhoModificar.getText());
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }}
else{
 JOptionPane.showMessageDialog(null,"Você deve localizar seu Deck para altera-lo!");
    
}


//CriaCarta alteraCarta = new CriaCarta();
//alteraCarta.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_botAlterarDeckMouseClicked

    private void txtCaminhoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaminhoModificarActionPerformed

    }//GEN-LAST:event_txtCaminhoModificarActionPerformed

    private void txtCaminhoModificarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCaminhoModificarPropertyChange

if(flagCaminho == 0){
flagCaminho = 1;
}
else{
flagCaminho = 0;
}
    }//GEN-LAST:event_txtCaminhoModificarPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
                 TelaInicial telaInicial = TelaInicial.getInstance();
                
                 telaInicial.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAlterarDeck;
    public javax.swing.JButton botCriarDeck;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtCaminhoModificar;
    public javax.swing.JTextField txtNomeDeck;
    // End of variables declaration//GEN-END:variables
}
